export const ApiConstants = {
  API_GET_CATEGORIES_LOAD: 'API_GET_CATEGORIES_LOAD',
  API_GET_CATEGORIES_SUCCESS: 'API_GET_CATEGORIES_SUCESS',
  API_GET_PRODUCTS_LOAD: 'API_GET_PRODUCTS_LOAD',
  API_GET_PRODUCTS_SUCCESS: 'API_GET_PRODUCTS_SUCCESS',
  API_GET_SELECTED_PRODUCT_SUCCESS: 'API_GET_SELECTED_PRODUCT_SUCCESS',
  API_GET_SELECTED_PRODUCT_LOAD: 'API_GET_SELECTED_PRODUCT_LOAD',
  API_GET_CATEGORY_SEARCH_LOAD: 'API_GET_CATEGORY_SEARCH_LOAD',
  API_GET_CATEGORY_SEARCH_SUCCESS: 'API_GET_CATEGORY_SEARCH_SUCCESS',
};
